/**
 * SurgiPal API
 * API to Access SurgiPal Data
 *
 * OpenAPI spec version: v1
 * Contact: raphael.thiney@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

'use strict';
import * as models from './models';

export interface DoctorInfo {
    

    id?: number;

    image?: string;

    firstName?: string;

    lastName?: string;

    officePhone?: string;

    pager?: string;

    companyName?: string;

    coordinatorName?: string;

    coordinatorPhone?: string;

    coordinatorEmail?: string;

    address?: string;

    suite?: string;

    city?: string;

    ppostalCode?: string;

    residentId?: number;

    yearsInPracticeId?: number;

    stateId?: number;

    countryId?: number;

    handednessId?: number;

    innerGloveSizeId?: number;

    outterGloveSizeId?: number;

    gloveTypeId?: number;

    gownSizeId?: number;

    fellow?: number;

    fellowSubspeciality?: string;

    stateTyped?: string;

    doubleGlove?: number;

    outterGloveTypeId?: number;

    notes?: string;

    specialtyId?: number;

    fellowshipTrained?: number;

    billingCoordinatorName?: string;

    billingCoordinatorPhone?: string;

    billingCoordinatorEmail?: string;

    fosUser?: models.FosUser;

    country?: models.Country;

    gloveType?: models.GloveType;

    gownSize?: models.GownSize;

    handedness?: models.Handedness;

    innerGloveSize?: models.GloveSize;

    outterGloveSize?: models.GloveSize;

    outterGloveType?: models.GloveType;

    resident?: models.Resident;

    specialty?: models.Specialty;

    state?: models.State;

    yearsInPractice?: models.YearsInPractice;
}
