/**
 * SurgiPal API
 * API to Access SurgiPal Data
 *
 * OpenAPI spec version: v1
 * Contact: raphael.thiney@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

'use strict';
import * as models from './models';

export interface FosUser {
    

    id?: number;

    userId?: string;

    doctorInfoId?: number;

    hospitalInfoId?: number;

    username?: string;

    usernameCanonical?: string;

    email?: string;

    emailCanonical?: string;

    enabled?: number;

    salt?: string;

    password?: string;

    lastLogin?: Date;

    locked?: number;

    expired?: number;

    expiredAt?: Date;

    confirmationToken?: string;

    passwordRequestedAt?: Date;

    roles?: string;

    credentialsExpired?: number;

    credentialsExpireAt?: Date;

    practiceId?: number;

    activationToken?: string;

    answer?: Array<models.Answer>;

    answerBoxDoctor?: Array<models.AnswerBox>;

    answerBoxHospital?: Array<models.AnswerBox>;

    answerBoxResponded?: Array<models.AnswerBox>;

    answerSuggestedFosUser?: Array<models.AnswerSuggested>;

    answerSuggestedSuggestingHospital?: Array<models.AnswerSuggested>;

    doctorHospitalDoctor?: Array<models.DoctorHospital>;

    doctorHospitalHospital?: Array<models.DoctorHospital>;

    doctorMessageSender?: Array<models.DoctorMessage>;

    doctorMessageUser?: Array<models.DoctorMessage>;

    surgeryDoctor?: Array<models.Surgery>;

    surgeryHospital?: Array<models.Surgery>;

    doctorInfo?: models.DoctorInfo;

    hospitalInfo?: models.HospitalInfo;

    practice?: models.Practice;

    user?: models.ApplicationUser;
}
